[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/go-check/check"
  revision = "20d25e2804050c1cd24a7eea1e7a6447dd0e74ec"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "v1.5.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "v1.4.0"

[[constraint]]
  name = "github.com/franela/goblin"
  version = "v0.0.2"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  name = "github.com/ToQoz/gopwt"
  version = "v2.0.0"

[[constraint]]
  name = "github.com/maxatome/go-testdeep"
  version = "v1.0.7"

[prune]
  go-tests = true
  unused-packages = true